# Site settings
title: "Hojiakbar Karimov"
description: "A resume for my future career position"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Hojiakbar Karimov"
resume_title:                   "Fullstack NodeJS developer"
resume_contact_email:           "kh.karimov96@gmail.com"
resume_contact_telephone:       "97 999 92 17 "
resume_contact_address:         "Maksim Gorkiy, Mirzo Ulug'bek district, Tashkent "
resume_header_contact_info: "false"
resume_header_intro: "<p>An accomplished Software Engineer specializing in Web development with small experience but huge knowledge in the full life cycle of the software design process, full stack development of various application in different platform and programming languages.</p>
  <p>Telegram number:+998 97 999 92 17</p>
  <p>Telegram number:@Reactuz</p>
  <p>Contact  number:+998 99 865 92 17</p>
"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://mredem96.github.io/resume-first/"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/hojiakbar-karimov-890901133/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
